# Generated by Django 2.2.2 on 2019-06-22 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newhome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Publication',
        ),
        migrations.RemoveField(
            model_name='student',
            name='book_name',
        ),
        migrations.AddField(
            model_name='student',
            name='book_00name',
            field=models.ForeignKey(help_text='name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='newhome.Book'),
        ),
    ]
