# Generated by Django 2.2.2 on 2019-06-19 10:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(help_text='Author Name', max_length=100, null=True)),
                ('total_book_written', models.CharField(choices=[('1', 'One'), ('2', 'two'), ('3', 'Three'), ('4', 'Four'), ('5', 'five')], max_length=1, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Birth')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Death')),
                ('timestamp', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Book Publication Name', max_length=100)),
                ('Address', models.CharField(help_text='Publication address', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='generated unique id for book', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Book Name', max_length=100, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateField(auto_now=True)),
                ('Publication', models.ManyToManyField(help_text='Publication of book', to='home.Publication')),
                ('book_author', models.ForeignKey(help_text='Book Author', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Author')),
            ],
        ),
    ]
